### ISSUE TITLE
Making a team the owner of the project

### ISSUE THREAD

**Issue by josojo** [bh2smith/duneapi#62]
I think the project is really great and you have done great work.

But I think it would be better if a whole team would manage the package, as then it can be updated quicker, even if you are on vacation.

**Comment by bh2smith** [comment]
I will transfer the ownership asap.

**Comment by bh2smith** [comment]
Since the new dune-client is now officially supported by the organization and this will be deprecated very soon, I won't proceed with this issue. I hope this is ok.
