### ISSUE TITLE
RuntimeError: ('Dune post failed with', <Response [404]>)

### ISSUE THREAD

**Issue by rolandgvc** [bh2smith/duneapi#65]
I've started getting the error this morning, any ideas what went wrong with the API?

**Comment by bh2smith** [comment]
Yes thanks for reporting! Remember that this is an unofficially supported API on Dune's side and that they reserve the right to change it at any time without notice. We are aware of the issue and actively trying to adapt (will redeploy ASAP).

**Comment by rolandgvc** [comment]
I've already applied for a key but didn't hear back yet :( Thank you for helping out with this 🙏
