### ISSUE TITLE
V2 endpoints?

### ISSUE THREAD

**Issue by rolandgvc** [bh2smith/duneapi#67]
Hi team, thanks again for the work on this API. I couldn't figure out how to send the queries to Dune Engine V2, the graphql endpoint and tokens all look the same. In particular, I'm trying to query the `erc1155_ethereum.evt_TransferSingle` table, as the ones from V1 are all missing some of the data 🤷🏻‍♂️ Any ideas?

**Comment by bh2smith** [comment]
V2 is not supported by this project, but we have already made a Proper Dune Client for V2 (using their officially supported API service).

It is built in a way that is VERY similar to this so migration should be easy:

Check it out https://github.com/cowprotocol/dune-client

**Comment by rolandgvc** [comment]
Thanks @bh2smith, if only I had a key! 🥲

**Comment by bh2smith** [comment]
I think you can contact Dune about this by email 

email api@dune.com with your username requesting for keys

**Comment by rolandgvc** [comment]
I've been in touch with their DevRel, still on the waitlist :(
